### ISSUE TITLE
BUG: No samples!! :D

### ISSUE THREAD

**Issue by onirtuen** [NateRickard/Azure.Android.Samples#1]
Hi NateRickard,

I'm trying to set up a really simple connection with the Azure Cosmos DB to no avail. I came across your repo cosmos_db_example and after I run it I get this error:

```java
04-20 16:04:13.317 7784-7784/microsoft.cosmos_db_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: microsoft.cosmos_db_example, PID: 7784
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'com.microsoft.azureandroid.data.model.Resource[] com.microsoft.azureandroid.data.model.ResourceList.getItems()' on a null object reference
                                                                               at microsoft.cosmos_db_example.Activities.DatabaseActivity$4.lambda$null$0$DatabaseActivity$4(DatabaseActivity.java:179)
                                                                               at microsoft.cosmos_db_example.Activities.DatabaseActivity$4$$Lambda$1.run(Unknown Source)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I tried to change DBConstants to match my Azure account/db/collections but it didn't help - same error occurred. This is because resource returned by response is null. Any advice on this?

**Comment by NateRickard** [comment]
@onirtuen Apologies, I was not watching this repo and missed this issue.

If you're still trying to use it, can you send the code for the call you're trying to make?  Also, make sure you've [initialized the library with a valid database name and master key](https://github.com/Azure/Azure.Android/blob/4f2767cd6ed0c9d22a7eaec096773e5c7c330a2f/Example/AzureDataAndroidExample/app/src/main/java/com/azure/mobile/azuredataandroidexample/App.kt#L19).  The db/key are left blank in that sample since they are unique to each person's Azure resources.
